classroom/urls.py
from django.urls import path
from .views import HomeView, ThankYou, ContactFormView, TeacherCreateView, TeacherListView, TeacherDetailView, \
    TeacherUpdateView, TeacherDeleteView

app_name = 'classroom'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),  # path expects a function
    path('thank_you/', ThankYou.as_view(), name='thank_you'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('create_teacher/', TeacherCreateView.as_view(), name='create_teacher'),
    path('list_teacher/', TeacherListView.as_view(), name='list_teacher'),
    path('teacher_detail/<int:pk>', TeacherDetailView.as_view(), name='detail_teacher'),
    path('update_teacher/<int:pk>', TeacherUpdateView.as_view(), name='update_teacher'),
    path('delete_teacher/<int:pk>', TeacherDeleteView.as_view(), name='delete_teacher')
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls'))
]

classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

classroom/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from classroom.models import Teacher
from classroom.forms import ContactForm

# Create your views here.
class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class ThankYou(TemplateView):
    template_name = 'classroom/thank_you.html'

class TeacherCreateView(CreateView):
    model = Teacher
    # model_form.html - in this case teacher_form.html
    # it will automatically run .save() after all fields are validated
    fields = "__all__"
    success_url = reverse_lazy('classroom:thank_you')

class TeacherListView(ListView):
    # model_list.html - teacher_list.html
    model = Teacher
    queryset = Teacher.objects.all().order_by('first_name')

    context_object_name = "teacher_list"

class TeacherDetailView(DetailView):
    # RETURN ONLY ONE MODEL ENTRY PK
    # model_detail.html
    model = Teacher
    # PK --> {{teacher}}

class TeacherUpdateView(UpdateView):
    # SHARE model_form.html --- PK
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:list_teacher')

class TeacherDeleteView(DeleteView):
    # Form --> Confirm Delete Button
    # default template name
    # model_confirm_delete.html
    model = Teacher
    success_url = reverse_lazy('classroom:list_teacher')




class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'

    # URL NOT a template.html
    success_url = reverse_lazy('classroom:thank_you')

    # what to do with a form
    def form_valid(self, form):
        print(form.cleaned_data['name'])
        return super().form_valid(form)

classroom/templates/classroom/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
        
    </form>
    
</body>
</html>

classroom/templates/classroom/home.html
<h1>Welcome to home.html</h1>
<ul>
    <li><a href="{% url "classroom:thank_you" %}">Thank you page</a></li>
    <li><a href="{% url "classroom:contact" %}">Contact form page</a></li>
    <li><a href="{% url "classroom:create_teacher" %}">Create New Teacher page</a></li>
    <li><a href="{% url "classroom:list_teacher" %}">This is list teacher page</a></li>
</ul>

classroom/templates/classroom/teacher_confirm_delete.html
<h1>Are you sure you want to delete this teacher?</h1>
<h2>{{ teacher }}</h2>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm delete">
</form>

classroom/templates/classroom/teacher_detail.html
<h1>Detail view for the teacher</h1>
{{ teacher }}

classroom/templates/classroom/teacher_form.html
<h1>Teacher Form</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

classroom/templates/classroom/teacher_list.html
<h1>List of teachers</h1>
<ul>
    {% for teacher in teacher_list %}
        <li>
            <a href="/classroom/teacher_detail/{{ teacher.id }}">{{ teacher.first_name }} {{ teacher.last_name }}</a>
            <ul>
                <li><a href="/classroom/update_teacher/{{ teacher.id }}">Update Information
                    for {{ teacher.first_name }}</a>
                </li>
            </ul>
            <ul>
                <li><a href="/classroom/delete_teacher/{{ teacher.id }}">Delete {{ teacher.first_name }}</a>
                </li>
            </ul>
        </li>
    {% endfor %}

</ul>

classroom/templates/classroom/thank_you.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <h1>Thank you</h1>
</body>
</html>